### ISSUE TITLE
Add test for certificate store conflicts

### ISSUE THREAD

**Issue by mrmueller** [Microsoft/adfsToolbox#16]
Test if Root certificates are located in the intermediate store and vice versa.

$rootconflicts = Get-ChildItem Cert:\LocalMachine\Root | Where-Object { $_.Issuer -ne $_.Subject }
$conflicts = Get-ChildItem Cert:\LocalMachine\CA | Where-Object { $_.Issuer -eq $_.Subject }

Source:
https://davidmcwee.com/2018/02/27/adfs-certificate-authentication-and-a-dirty-certificate-store/

**Comment by madhavpatel6** [comment]
@mrmueller thanks for opening an issue, we will look into adding a test to cover this scenario.

**Comment by madhavpatel6** [comment]
Added two new tests for ADFS and WAP.
