### ISSUE TITLE
WAP: Export-AdfsDiagnosticsFile fails

### ISSUE THREAD

**Issue by SteveT76** [Microsoft/adfsToolbox#44]
It appears WAP Export bug was re-introduced in version 1.0.4

Export works OK in verison 1.03

PS C:\Utils> Export-AdfsDiagnosticsFile -sslThumbprint "########################" -Verbose
VERBOSE: Export-AdfsDiagnosticsFile: Creating file ADFSDiagnosticsFile-20180926141632.json
VERBOSE: GenerateJSONDiagnosticData: Generating diagnostic data
VERBOSE: GenerateDiagnosticData: Binding each argument to relevant cmdlets
VERBOSE: GenerateDiagnosticData: Attempting to run cmdlet Test-AdfsServerHealth
Performing applicable health checks on your WAP server.
VERBOSE: IsTlsVersionEnabled: Checking if TLS 1.0 is enabled
VERBOSE: IsTlsVersionEnabled: The registry key for this TLS version does not exist at HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0
VERBOSE: IsTlsVersionEnabled: Checking if TLS 1.1 is enabled
VERBOSE: IsTlsVersionEnabled: The registry key for this TLS version does not exist at HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1
VERBOSE: IsTlsVersionEnabled: Checking if TLS 1.2 is enabled
VERBOSE: IsTlsVersionEnabled: The registry key for this TLS version does not exist at HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2
VERBOSE: TestTimeSync: Checking time synchronization.
VERBOSE: TestTimeSync: Detected that the current server is a WAP server.
VERBOSE: IsServerTimeInSyncWithReliableTimeServer: Comparing server time with reliable time server
VERBOSE: GET http://nist.time.gov/actualtime.cgi?lzbc=siqm9b with 0-byte payload
VERBOSE: received 62-byte response of content type text/xml
VERBOSE: IsServerTimeInSyncWithReliableTimeServer: Current reliable time server time UTC 09/26/2018 13:16:34
VERBOSE: IsServerTimeInSyncWithReliableTimeServer: Current server time UTC 09/26/2018 13:16:33
VERBOSE: IsServerTimeInSyncWithReliableTimeServer: Time difference in seconds 1
VERBOSE: TestProxySslBindings: Parameter AdfsSslThumbprint = c7f41c20872c8d856f912f10ddb58882ef34a468
VERBOSE: TestProxySslBindings: Attempting to get federation service name.
VERBOSE: TestProxySslBindings: Retrieved federation service name: signon.impellam.com.
VERBOSE: TestProxySslBindings: Retrieved ADFS Port: 443 TLS Port: 49443
VERBOSE: TestProxySslBindings: Attempting to validate expected SSL bindings.
VERBOSE: IsSslBindingValid: Validating SSL binding for signon.impellam.com:443.
VERBOSE: IsSslBindingValid: Successfully validated SSL binding for signon.impellam.com:443.
VERBOSE: IsSslBindingValid: Validating SSL binding for signon.impellam.com:49443.
VERBOSE: IsSslBindingValid: Successfully validated SSL binding for signon.impellam.com:49443.
Successfully completed all health checks.
GenerateDiagnosticData : Error running cmdlet ADFSToolbox\Test-AdfsServerHealth -sslThumbprint $sslThumbprint: Cannot find an overload for "TestResultsContainer" and the argument
count: "1".
At C:\Program Files\WindowsPowerShell\Modules\adfsToolbox-1.0.3\diagnosticsModule\Private\HelperUtilities.ps1:690 char:23
+ ... osticData = GenerateDiagnosticData -includeTrusts:$includeTrusts -ssl ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,GenerateDiagnosticData

VERBOSE: GenerateJSONDiagnosticData: Successfully generated diagnostic data
VERBOSE: Export-AdfsDiagnosticsFile: Outputting diagnostic data at C:\Utils\ADFSDiagnosticsFile-20180926141632.json
Please upload the diagnostic file located at C:\Utils\ADFSDiagnosticsFile-20180926141632.json to https://adfshelp.microsoft.com/DiagnosticsAnalyzer/Analyze.

**Comment by madhavpatel6** [comment]
Thanks for reporting the issue @SteveT76. I will get this fixed later today.

**Comment by madhavpatel6** [comment]
I have checked in a fix and released a new version to PowerShell gallery. Thank you again for reporting the issue.
