### ISSUE TITLE
Non Signed Script

### ISSUE THREAD

**Issue by garyjkane** [Microsoft/adfsToolbox#61]
When i try to run this script it says it is not signed, on customers who set thier policy to allow only RemoteSigned scripts this is an issue. Am i doing something wrong or should we expect scripts to be signed especially when they are publicised by microsoft?

**Comment by madhavpatel6** [comment]
Hi @garyjkane, currently the scripts for ADFS Toolbox are not signed. We are currently working on migrating this code once this is done we will publish officially signed scripts.
