### ISSUE TITLE
Module wrongly assumes samAccountName

### ISSUE THREAD

**Issue by danielniccoli** [Microsoft/adfsToolbox#73]
This module wrongly assumes that the samAccountName is substring of the userPrincipalName before the '@'. However, this is not always true. A user or service account can have the userPrincipalName `serviceaccount@ad.contoso.com` but the samAccountName can be completely different, e.g. `i-am-a-serviceaccou`.

In addition to that, in Active Directory the samAccountname is limited to 20 characters. Another limitation that is ignored.

If we follow the example above, the assumptions made in the code would lead the module to wrongfully report unhealthy configurations.

Some wrong parts in the code are

Here `$serviceAccount` may return a userPrincipalName. The following setspn command will return  the error `FindDomainForAccount: Call to DsGetDcNameWithAccountW failed with return value 0x00000525; Could not find account serviceaccount@ad.contoso.com`

```powershell
$serviceAccount = (gwmi win32_service -filter "name='adfssrv'").StartName;
# [...]
[array]$serviceAccountSPN = setspn -L $serviceAccount;
```
https://github.com/microsoft/adfsToolbox/blob/master/diagnosticsModule/Private/AdfsConfiguration.ps1#L59

Here you assume that the samAccountName is simply the part in the userPrincipalName before the '@', which may be a lucky guess, but is technical false.

```powershell
$serviceSamAccountName = $serviceAccountPartsUpn[0]
$serviceAccountDomain = TryGetDomainNameFromUpn $adfsServiceAccount
if ($serviceAccountDomain)
{
    $adfsServiceAccountFormatted = "$serviceAccountDomain\$serviceSamAccountName"
}
```
https://github.com/microsoft/adfsToolbox/blob/master/diagnosticsModule/Private/AdfsHealthChecks.ps1#L380

A possible solution would be to use Get-ADUser cmdlet.

```powershell
$u = Get-ADUser -Filter "samaccountname -eq '$serviceAccount'"
if (!$u) {
   Get-ADUser -Filter "userPrincipalName -eq '$serviceAccount'"
}
```

Those are just two of many wrong parts in the code where those assumptions are made.

**Comment by madhavpatel6** [comment]
Thanks for the feedback Borkason. We are aware of the many (incorrect) assumptions that this code has made. We have completely re-written these diagnostics tests in C# (in a private repo); and are planning on releasing the new module in the upcoming weeks.

**Comment by danielniccoli** [comment]
Great to hear. I assume this can be closed then.
